# Generated by Django 6.0.2 on 2026-02-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('articles_analyzed_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrendTopic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('article_count', models.IntegerField(default=0)),
                ('representative_articles', models.TextField(default='[]')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='trends.runlog')),
            ],
        ),
    ]
