from django.db import models

class RunLog(models.Model):
    id = models.AutoField(primary_key=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    articles_analyzed_count = models.IntegerField(default=0)
    status = models.CharField(max_length=20, default="PENDING") # PENDING, SUCCESS, FAILED
    
    def __str__(self):
        return f"Run {self.id} - {self.timestamp}"

class TrendTopic(models.Model):
    id = models.AutoField(primary_key=True)
    run = models.ForeignKey(RunLog, on_delete=models.CASCADE, related_name='trends')
    label = models.CharField(max_length=255, blank=True, null=True) # e.g. "Topic 0" or custom label
    keywords = models.TextField() # Stored as comma-separated or JSON string
    summary = models.TextField(blank=True, null=True) # Generated by LLM
    article_count = models.IntegerField(default=0)
    
    # We store representative articles as a JSON list to avoid a separate table for thousands of articles
    # Schema: [{"title": "...", "url": "...", "source": "..."}]
    representative_articles = models.TextField(default="[]") 
    
    def __str__(self):
        return f"{self.label} ({self.article_count})"
